spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: dbc:postgresql://db:5432/db
    username: user
    password: pass
mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
jwt:
  public:
    key: classpath:app.key.pub
  private:
    key: classpath:app.key
