spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
    password:
mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
jwt:
  public:
    key: classpath:app.key.pub
  private:
    key: classpath:app.key
